# Generated by Django 5.2.4 on 2025-08-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('finding', models.TextField()),
                ('reasons', models.TextField()),
                ('root_cause', models.TextField()),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('measures', models.TextField()),
                ('ca_score', models.IntegerField()),
                ('ca_status', models.CharField(max_length=50)),
                ('ca_comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
