# Generated by Django 5.2.4 on 2025-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisrun_analysishistory_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishistory',
            name='ca_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
