# Generated by Django 5.2.4 on 2025-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_analysishistory_ca_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishistory',
            name='ca_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysishistory',
            name='ca_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
